i = input("enter num1:" )
j = input("enter num2:" )
sum = int(i) + int(j)
product = int(i) * int(j)
diffrence  = int(i) - int(j)
divide = int(i) / int(j)
print(f"sum = {sum}")
print(f"product = {product}")
print(f"diffrence = {diffrence}")
print(f"divide = {divide}")
print(type(i))
print(type(j))